#! /usr/bin/env bash

source secret.sh

redis_name=redis
redis_port=6379
docker run -d \
  --name $redis_name \
  -p $redis_port:$redis_port \
  redis
trap "docker rm -f $redis_name" EXIT

docker run -it \
  -v $(pwd)/src:/usr/src/app \
  -w /usr/src/app \
  -p 3000:80 \
  -e TWITTER_CLIENT_ID=$TWITTER_CLIENT_ID \
  -e TWITTER_CLIENT_SECRET=$TWITTER_CLIENT_SECRET \
  -e SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID \
  -e SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET \
  \
  --link $redis_name:redis \
  -e REDIS_HOST=redis \
  -e REDIS_PORT=$redis_port \
  node bash
